version: 0.2

phases:
  install:
    commands:
      - apt update
      - apt install -y jq
      - pip install --upgrade awscli
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
  pre_build:
    commands:
      -   | 
       aws dynamodb scan --table-name tenant-quota | jq '{input: (reduce .Items[] as $item ({}; .[$item.TenantId.S] = {
       QuotaOffeset: ($item.QuotaOffeset.N | tonumber),
       QuotaPeriod: $item.QuotaPeriod.S,
       RateLimit: ($item.RateLimit.N | tonumber),
       BurstLimit: ($item.BurstLimit.N | tonumber),
       QuotaLimit: ($item.QuotaLimit.N | tonumber)
       }))}' > variables.tfvars.json
  build:
    commands:
      - cd terraform
      - terraform init
      - terraform apply -auto-approve -var-file=variables.tfvars.json